class windows(object):
    window_list = [
        "Castle East",
        "Castle South East",
        "Castle South West",
        "Garage North",
        "Garage South",
        "Guest North East",
        "Guest North West",
        "Guest West North",
        "Guest West South",
        "Kitchen East",
        "Kitchen North East",
        "Kitchen North West",
        "Library South East",
        "Library South West",
        "Library West North",
        "Library West South",
        "Livingroom North East",
        "Livingroom North West",
        "Livingroom West North",
        "Livingroom West South",
        "Master East",
        "Master North East",
        "Master North West",
        "Office South East",
        "Office South West",
        "Office West North",
        "Office West South",
        "Rotunda Skylight 1",
        "Rotunda Skylight 2",
        "Sitting East",
        "Sitting South East",
        "Sitting South West"
    ]    
    direction = ["down", "up"]
